with open('error.txt', 'w') as errorbox:
    errorbox.write("AN ERROR HAS OCCURED")